defaults: &defaults
  working_directory: /go/src/github.com/monax/hoard
  docker:
    - image: quay.io/monax/hoard:build

tag_filters: &tags_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

setup_docker: &setup_docker
  version: 17.11.0-ce

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - run: echo $CIRCLE_PULL_REQUESTS
      - checkout
      - run: make test
      - run: make build

  # test_integration:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run: make test_integration

  test_gcp_integration:
    working_directory: /go/src/github.com/monax/hoard
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
      - run: |
          gcloud auth activate-service-account --key-file=/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - checkout
      - run: make test_integration

  ensure_vendor:
    <<: *defaults
    steps:
      - checkout
      - run: make ensure_vendor

  build_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *setup_docker
      - run: make docker_build

  release_dev:
    <<: *defaults
    steps:
      - setup_remote_docker:
          <<: *setup_docker
      - checkout
      - run: make release_dev

  release:
    <<: *defaults
    steps:
      - setup_remote_docker:
          <<: *setup_docker
      - checkout
      - run: make release


workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            <<: *tags_filters

      - test_gcp_integration:
          filters:
            <<: *tags_filters

      - ensure_vendor:
          filters:
            <<: *tags_filters

      - build_docker:
          filters:
            <<: *tags_filters

      - release_dev:
          requires:
          - test
          - test_gcp_integration
          filters:
            branches:
              only: develop

      - release:
          requires:
          - test
          - test_gcp_integration
          filters:
            <<: *tags_filters
            branches:
              ignore: /.*/
