defaults: &defaults
  working_directory: /go/src/github.com/monax/hoard
  docker:
    - image: quay.io/monax/hoard:build

tag_filters: &tags_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

setup_docker: &setup_docker
  version: 17.11.0-ce

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - run: echo $CIRCLE_PULL_REQUESTS
      - checkout
      - run: make test
      - run: make build

  build_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          <<: *setup_docker
      - run: make docker_build

  test_js:
    <<: *defaults
    steps:
      - checkout
      - run: make npm_install
      - run: make test_js

  test_integration:
    <<: *defaults
    steps:
      - setup_remote_docker:
          <<: *setup_docker
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > /tmp/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
      - run: make test_integration

  release:
    <<: *defaults
    steps:
      - setup_remote_docker:
          <<: *setup_docker
      - checkout
      - run: make release

workflows:
  version: 2

  test_and_release:
    jobs:
      - test:
          filters:
            <<: *tags_filters

      - build_docker:
          filters:
            <<: *tags_filters

      - test_js:
          filters:
            <<: *tags_filters

      - test_integration:
          filters:
            <<: *tags_filters
            branches:
              only:
              - develop
              - master

      - release:
          requires:
          - build_docker
          - test_integration
          - test
          filters:
            <<: *tags_filters
            branches:
              only:
              - master
