version: '3'
services:
  hoard:
    build: ..
    # These are set in the tests
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GOOGLE_APPLICATION_CREDENTIALS
      - HOARD_JSON_CONFIG
    ports:
      - "53431:53431"
    volumes:
      - /tmp:/config
  hoarctl:
    build: ..
    links:
      - hoard
    # note: '$$' escapes '$'
    command: sh -c '[ $$(echo "marmottes" | hoarctl -a tcp://hoard:53431 put | hoarctl -a tcp://hoard:53431 get) = "marmottes" ]'
